version: '3.8'
services:
  wa-bot:
    build: .
    container_name: wa-bot-claude
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - CHROME_PATH=/usr/bin/chromium-browser
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./wa-bot.data.json:/app/wa-bot.data.json
      - ./_IGNORE_wa-bot:/app/_IGNORE_wa-bot
  db:
    image: postgres:15-alpine
    container_name: wa-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
